### ISSUE TITLE
Converting the python code to be Python3 compatible 

### ISSUE THREAD

**Issue by pramodk** [HumanBrainProject/olfactory-bulb-3d#11]
Most of the HPC systems now have Python3 as default. Currently code is Python 2 and not compatible with Python3. This makes installation / testing bit cumbersome on different platforms.

@mmigliore: I have minimal knowledge of this model and especially Python. Could someone help with making this python code compatible with Python3? (I think wouldn't take that much efforts, most of the things should be straightforward).

[Installing and running test model](https://github.com/HumanBrainProject/olfactory-bulb-3d/blob/master/README.md) is same as before.

Thanks!

cc: @lbologna @iomaganaris

**Comment by mmigliore** [comment]
Dear Pramod
Michael Hines is going to do it.
Could you confirm the link to the code?
Best
Michele


Il ven 18 set 2020, 08:58 Pramod Kumbhar <notifications@github.com> ha
scritto:

**Comment by mmigliore** [comment]
running only with python3 will be ok.

**Comment by pramodk** [comment]
this is already done and code is merged into master
