### ISSUE TITLE
Modules not available

### ISSUE THREAD

**Issue by lbologna** [HumanBrainProject/olfactory-bulb-3d#15]
Hello @pramodk,

I am trying to run the example code reported in the README (https://github.com/HumanBrainProject/olfactory-bulb-3d/blob/master/README.md) on marconi100, but it seems that some module is not available anymore ('pgi/19.10--binary') and some other is oudated (cmake/3.17.1 to be replaced with cmake/3.20.0).
In addition, this folder "/m100_work/Pra18_4575_0/software/gpu/pgi/localrc" does not exist anymore.

Could you please update the paths/modules so that I can perform a simple test?

Thank you!

**Comment by lbologna** [comment]
Hello @pramodk,

Did you have the chance to have a look at this?
If you have a simple script that you can pass me to run a small (short) test on m100, that would be very helpful too.

Thank you.

**Comment by lbologna** [comment]
Modules updated.
Closing issue.

**Comment by pramodk** [comment]
Hello @lbologna!

I have somehow missed your previous GitHub comments from last year. Apologies! 

We have prepared/tested this model (esp branch in the PR #12) on CPU as well as GPU. So if you will have any issues, please contact me or @jorblancoa or @iomaganaris.
