### ISSUE TITLE
compilation issue on marconi100

### ISSUE THREAD

**Issue by fcavarretta-ualr** [HumanBrainProject/olfactory-bulb-3d#20]
**The CoreNEURON installation on Marconi is not anymore available at the directory indicated in the README.**
**Also, the directory /m100_work/Pra18_4575_0/ is not longer existing.**
**Trying to compile CoreNEURON using the following script:**

module load profile/archive
module load profile/base
module load profile/advanced
module load pgi/19.10--binary gnu/8.4.0 cuda/10.1
module load spectrum_mpi/10.3.1--binary boost/1.72.0--spectrum_mpi--10.3.1--binary
module load cmake/3.20.0

export PGI_LOCALRC=/m100_work/Pra18_4575_0/software/gpu/pgi/localr
export OMPI_CXX=pgc++
export OMPI_CC=pgcc
export CC=mpicc
export CXX=mpicxx
rm -rf nrn
git clone https://github.com/neuronsimulator/nrn.git
mkdir -p nrn/build && cd nrn/build
git checkout 6f4ae452d771521ddaa357bb2ed8eb33c3f4a2d0

cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/install \
        -DNRN_ENABLE_INTERVIEWS=OFF \
        -DNRN_ENABLE_RX3D=OFF \
        -DNRN_ENABLE_CORENEURON=ON \
        -DPYTHON_EXECUTABLE=`which python3` \
        -DCORENRN_ENABLE_MPI=ON \
        -DCORENRN_ENABLE_OPENMP=OFF \
        -DCORENRN_ENABLE_GPU=ON \
        -DNRN_ENABLE_BINARY_SPECIAL=ON \
        -DNRN_ENABLE_SHARED=OFF \
        -DNRN_ENABLE_INTERNAL_READLINE=ON
        -DPYTHON_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
        -DPYTHON_LIBRARY=$(python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") \

make -j8
make install

**I get this error:**

Scanning dependencies of target nrniv
[ 86%] Built target scopmath
5 errors detected in the compilation of "/tmp/tmpxft_00198ff2_00000000-8_nrnran123.compute_52.cpp1.ii".
[ 86%] Built target nrniv
CMake Error at cudacoreneuron_generated_nrnran123.cu.o.RelWithDebInfo.cmake:276 (message):
  Error generating file
  /m100/home/userexternal/fcavarre/nrn/build/external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/utils/randoms/./cudacoreneuron_generated_nrnran123.cu.o

make[2]: *** [external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/build.make:495: external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/utils/randoms/cudacoreneuron_generated_nrnran123.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1177: external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Building python module with: /usr/bin/python3
[ 86%] Built target hoc_module
make: *** [Makefile:156: all] Error 2
[  0%] Performing build step for 'mod2c'
[100%] Built target mod2c_core
[  0%] Performing install step for 'mod2c'
[100%] Built target mod2c_core
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /m100/home/userexternal/fcavarre/nrn/build/share/nrnunits.lib
-- Up-to-date: /m100/home/userexternal/fcavarre/nrn/build/bin/mod2c_core
[  0%] Completed 'mod2c'
[  1%] Built target mod2c
[  1%] Built target link_units
[  2%] Built target scopmath
[  3%] Built target kin_deriv_header
[  3%] Building NVCC (Device) object external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/utils/randoms/cudacoreneuron_generated_nrnran123.cu.o
/m100/prod/opt/compilers/gnu/8.4.0/none/include/c++/8.4.0/type_traits(335): error: identifier "__ieee128" is undefined

/usr/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined

/usr/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"

/m100/prod/opt/compilers/gnu/8.4.0/none/include/c++/8.4.0/bits/std_abs.h(101): error: identifier "__ieee128" is undefined

/m100/prod/opt/compilers/gnu/8.4.0/none/include/c++/8.4.0/bits/std_abs.h(102): error: identifier "__ieee128" is undefined

5 errors detected in the compilation of "/tmp/tmpxft_001990c4_00000000-8_nrnran123.compute_52.cpp1.ii".
CMake Error at cudacoreneuron_generated_nrnran123.cu.o.RelWithDebInfo.cmake:276 (message):
  Error generating file
  /m100/home/userexternal/fcavarre/nrn/build/external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/utils/randoms/./cudacoreneuron_generated_nrnran123.cu.o

make[2]: *** [external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/build.make:495: external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/utils/randoms/cudacoreneuron_generated_nrnran123.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1177: external/coreneuron/coreneuron/CMakeFiles/cudacoreneuron.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by pramodk** [comment]
Hello @FrancescoCavarretta,

It's true that neuron+coreneuron is changing faster and also the module on the cineca system software stack. So old instructions need an update.

But before trying the GPU version with coreneuron, could you briefly tell me what you plan to test/benchmark and which branches? 
 We can then update instructions accordingly. cc: @iomaganaris

**Comment by FrancescoCavarretta** [comment]
Hi Pramod, Ioannis:

Yes, I would like to run simulations on Marconi100 using the 2to3 branch.

What is the difference between neuron and neuron-nightly?

In the meantime, on marconi100, I have also tried to run pip install neuron and pip install neuron-nightly but none worked out, and their packages are not retrievable.

At this point, I think that the best way to solve the issue is to have you installing neuron on marconi100. I bet you could do it really fast.

Thanks so much for your help!

-Francesco

**Comment by pramodk** [comment]
thank for the info @FrancescoCavarretta! 

Which active project we have on Marconi100? May be I can ask Michele to temporarily add me there so that I can build and test the installation.

**Comment by FrancescoCavarretta** [comment]
Hi Pramod:
Indeed, I am working with Michele Migliore. He has active projects on Marconi100.

**Comment by pramodk** [comment]
@FrancescoCavarretta : sorry for delay again. Today I got time to revisit this. I now have updated the [README file](https://github.com/HumanBrainProject/olfactory-bulb-3d/tree/2to3) in the `2to3` branch. The instructions there should help you to build neuron and coreneuron with latest modules available.

I could install this in a project directory but I / Ioannis are not part of any project. I will email Michele to see if we could be added to help running this model properly. I think it would be better to do test runs together so that everything works as expected performancewise.

If you have any questions, let us know!

**Comment by FrancescoCavarretta** [comment]
The compilation was successful! I will proceed with testing myself. Thank you so much!

**Comment by pramodk** [comment]
Ok, glad to hear!

Just to mention, we can verify / discuss GPU performance related aspects bit later. First, very helpful thing would be to verify if the results are looking OK.
